### ISSUE TITLE
CF Stack "nrf-asset-tracker-webapp" deployment fails due to missing export

### ISSUE THREAD

**Issue by kdoren** [NordicSemiconductor/asset-tracker-cloud-aws-js#1429]
I tried deploying nRF asset tracker.  

CF stacks "CDKToolkit" and "nrf-asset-tracker" deployed successfully.

CR stack "nrf-asset-tracker-webapp" failed, with the following event:
```
No export named nrf-asset-tracker:networkSurveyGeolocationApiUrl found. Rollback requested by user.
```

It appears that this stack requires an export nrf-asset-tracker:networkSurveyGeolocationApiUrl which is not provided by stack "nrf-asset-tracker".
Where is this export provided?

```
git checkout v40.4.8
npm ci
npx cdk deploy --all

fails with:

nrf-asset-tracker-webapp: deploying... [2/2]
nrf-asset-tracker-webapp: creating CloudFormation changeset...

 ?  nrf-asset-tracker-webapp failed: Error: The stack named nrf-asset-tracker-webapp failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at FullCloudFormationDeployment.monitorDeployment (/home/kevind/nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:403:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/kevind/nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:406:152469)
    at async /home/kevind/nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:406:136265

 ? Deployment failed: Error: The stack named nrf-asset-tracker-webapp failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at FullCloudFormationDeployment.monitorDeployment (/home/kevind/nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:403:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/kevind/nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:406:152469)
    at async /home/kevind/nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:406:136265

The stack named nrf-asset-tracker-webapp failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
```

**Comment by coderbyheart** [comment]
But it is exported: https://github.com/NordicSemiconductor/asset-tracker-cloud-aws-js/blob/b51068b0b907fb463f7e6f687b817190f1539f84/cdk/stacks/AssetTracker/stack.ts#L553-L556

However, this was only recently added [in version 40.0.0](https://github.com/NordicSemiconductor/asset-tracker-cloud-aws-js/blame/saga/cdk/stacks/AssetTracker/stack.ts#L553-L556). Which version of nRF Asset Tracker for AWS do you have deployed?

**Comment by kdoren** [comment]
Thanks.  I'm using latest release v40.4.8.

The export you reference above appears to be conditioned on "nrfcloudGroundFix" being defined.  In my case I don't have any nrfCloud API key defined, which I believe leaves nrfcloudGroundFix undefined.  Is it a requirement for deployment?

In asset-tracker-cloud-aws-js/cdk/stacks/AssetTracker/stack.ts:
```
                // Network Surveys Storage
                enabledInContext(this.node)({
                        key: 'nrfcloudGroundFix',
                        component: 'nRF Cloud API (ground fix)',
                        onUndefined: 'disabled',
                        onEnabled: () => {

                               <<< other defs >>>

                                new CloudFormation.CfnOutput(this, 'networkSurveyGeolocationApiUrl', {
                                        value: networkSurveysGeolocationApi.url,
                                        exportName: StackOutputs.networkSurveyGeolocationApiUrl,
                                })
                        },
                })
```

**Comment by coderbyheart** [comment]
Ah, correct, it is a requirement in the web application but optional in the backend. I'll change that. Might take a few weeks because I am busy with other projects.

See https://github.com/NordicSemiconductor/asset-tracker-cloud-app-aws-js/issues/566

**Comment by barrybingo** [comment]
Even with latest commits this bug is still active.

**Comment by coderbyheart** [comment]
Are you using the `saga` branch?

Can you share the output of your `npx cdk deploy`?

Because [it is now behind a flag check](https://github.com/NordicSemiconductor/asset-tracker-cloud-aws-js/blob/4e27c62016f63ff3901b3493ff34a654211a404b/cdk/stacks/WebApp.ts#L86-L96).

**Comment by barrybingo** [comment]
Yes using saga branch, just cloned today as I'm following the guide.

`
$ npx cdk deploy 

 ❌  nrf-asset-tracker-webapp failed: Error: The stack named nrf-asset-tracker-webapp failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at FullCloudFormationDeployment.monitorDeployment (/nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:412:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:415:153172)
    at async /nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:415:136968

 ❌ Deployment failed: Error: The stack named nrf-asset-tracker-webapp failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at FullCloudFormationDeployment.monitorDeployment (/nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:412:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:415:153172)
    at async /nrf-asset-tracker/aws/node_modules/aws-cdk/lib/index.js:415:136968

The stack named nrf-asset-tracker-webapp failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
`

**Comment by coderbyheart** [comment]
Can you share the error events from the CloudFormation console for the `nrf-asset-tracker-webapp` stack?

**Comment by barrybingo** [comment]
Do you mean this?

![image](https://github.com/NordicSemiconductor/asset-tracker-cloud-aws-js/assets/1028388/4d5dcd65-cf19-4592-8d86-ebaccc9963ed)

**Comment by coderbyheart** [comment]
Yes, thanks.

**Comment by barrybingo** [comment]
Thanks. that seems to work, I get an access denied for cloudfront distribution but that's probably something on my end.

**Comment by coderbyheart** [comment]
It's probably empty and you need to publish the web application there.
