### ISSUE TITLE
Error: System not configured: /nrf-asset-tracker/thirdParty/sentry!

### ISSUE THREAD

**Issue by barrybingo** [NordicSemiconductor/asset-tracker-cloud-aws-js#1473]
Hiya,
Following the guide there is a step to run `./cli.sh web-app-config` which gives me the following error:

`
$ ./cli.sh web-app-config
(node:112128) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:112128) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)

 ERROR  web-app-config failed!
 ERROR  Error: System not configured: /nrf-asset-tracker/thirdParty/sentry!
`

I guess this is sentry.io?  I could not find how to configure this for the web app so I removed the reference from  cli/commands/web-app-config.ts and util/settings.ts.  Output then worked and I could progress with the guide.

**Comment by coderbyheart** [comment]
Thanks for reporting. This was an oversight, and yes, Sentry.io integration is optional, so this should not have caused an error.
