### ISSUE TITLE
Unwiredlabs RAT nbiot instead of lte

### ISSUE THREAD

**Issue by pfried** [NordicSemiconductor/asset-tracker-cloud-aws-js#41]
https://github.com/NordicSemiconductor/asset-tracker-cloud-aws-js/blob/46ae5e59a340c8cc74c1c893885265ec542d9920/cellGeolocation/stepFunction/unwiredlabs.ts#L100

Any reason you did not choose `nbiot` for the radio key?

**Comment by pfried** [comment]
Ah I see, it says private beta, but in fact it is working with a developer account

**Comment by coderbyheart** [comment]
The `nbiot` radio mode has been around for a while but I did never work for the data I was testing with.
It seems that they use different cell IDs.

This works (`lte`):

```
http https://eu1.unwiredlabs.com/v2/process.php <<< '{                                                                                                                   
    "token": "***",
    "radio": "lte",                                
    "mcc": 242,      
    "mnc": 1,                 
    "cells": [{
        "lac": 30401,
        "cid": 20227
    }]
}'
```

```json
{
    "accuracy": 5947,
    "balance": 100,
    "fallback": "scf",
    "lat": 63.434302,
    "lon": 10.472467,
    "status": "ok"
}
```

while using `nbiot` does not locate the cell.

**Comment by coderbyheart** [comment]
@pfried do you have example data from from an NB-IoT network that works with `nbiot` but not with `ltem`?

**Comment by pfried** [comment]
```
{
    "token": "***",
    "radio": "nbiot",
    "signal": -55,
    "mcc": 262,
    "mnc": 1,
    "cells": [{
         "lac": 54057,
        "cid": 34072331
    }]
}
```

This one returns only with nbiot, but it shows a fallback on the result, but I actually do not know what the `ncf` means.

```
{
    "status": "ok",
    "balance": 98,
    "lat": 48.780949,
    "lon": 9.158443,
    "accuracy": 3657,
    "fallback": "ncf"
}
```

**Comment by coderbyheart** [comment]
I've reached out to UnwiredLabs support to get a documentation for the fallback.

**Comment by coderbyheart** [comment]
I think it makes sense to implement using the `nbiot` radio mode for UnwiredLabs queries, in case the device is using NB-IoT.

Adding the `signal` parameter also is a good idea.

**Comment by coderbyheart** [comment]
@pfried The latest release adds support for NB-IoT cells locations.

If you have a lot of existing cell data, you might want to migrate the entries in the cache table, see https://github.com/NordicSemiconductor/asset-tracker-cloud-aws-js/pull/111#issuecomment-789048815
